# Generated by Django 5.1.15 on 2026-09-12 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=32, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('image_path', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField(blank=True)),
                ('ocr_source', models.CharField(choices=[('sidecar', 'Native text'), ('tesseract', 'Tesseract OCR'), ('manual', 'Manually entered')], default='sidecar', max_length=20)),
                ('phash', models.CharField(blank=True, db_index=True, max_length=20)),
                ('vendor_raw', models.CharField(blank=True, max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('invoice_no', models.CharField(blank=True, db_index=True, max_length=40)),
                ('invoice_date', models.DateField(blank=True, db_index=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('doc_confidence', models.FloatField(default=0.0)),
                ('arithmetic_ok', models.BooleanField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('noise_tier', models.IntegerField(default=0)),
                ('template_id', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('gstin', models.CharField(blank=True, db_index=True, max_length=15)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=32, unique=True)),
                ('claimed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('NEEDS_INFO', 'Needs Info'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('duplicate_group', models.IntegerField(blank=True, db_index=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='expenses.claim')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=16, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=60)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_code'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='expenses.employee'),
        ),
        migrations.AddField(
            model_name='claim',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='expenses.receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='expenses.vendor'),
        ),
        migrations.CreateModel(
            name='VendorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='expenses.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('band', models.CharField(db_index=True, max_length=10)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('rules_fired', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed duplicate'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_as_a', to='expenses.claim')),
                ('matched_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_as_b', to='expenses.claim')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['band', 'status'], name='expenses_du_band_706193_idx')],
                'unique_together': {('claim', 'matched_claim')},
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('pattern_id', models.CharField(blank=True, max_length=40)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('needs_review', models.BooleanField(default=False)),
                ('corrected_value', models.CharField(blank=True, max_length=200)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted', to='expenses.receipt')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('receipt', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['invoice_no', 'total'], name='expenses_re_invoice_beebdc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendoralias',
            unique_together={('vendor', 'alias')},
        ),
    ]
