# Generated by Django 5.1.15 on 2026-09-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='currency',
            field=models.CharField(blank=True, db_index=True, default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='receipt',
            name='currency_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
