# Generated by Django 5.1 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_receipt_currency_receipt_currency_confidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="image_blob",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="receipt",
            name="image_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
