# Generated by Django 5.1 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_receipt_image_blob_receipt_image_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="object_storage_bucket",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="receipt",
            name="object_storage_etag",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="receipt",
            name="object_storage_key",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
